# Default values for promehteus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/abitocchi/pipeline-image
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: prom-exp-promehteus-exporter-devops.apps-crc.testing

  tls:
    enabled: true
    termination: edge

    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAougPijFsUobKtQLlsrI0xHA30haHuPQpj9ys1hfUkza2ZOp2
      cOoCxR0r9QKxDV6rDGwu/lENruMyt67abVosQ66Xyq5tPR3F9G8O5vYP1j89bipt
      7o46EgSFRISFNDTedLNrQ7Y+TEBeR8tcVwfdpJ6Bx24UrqZ7vjsyU8dgtQ87PC49
      LdYQ2VcdRlrvTnONNSQrlH2zDjiWkLcalc/zbFUvxBvBqMAiAFomRaQx+i49kwR0
      yAP6Y4dl+m4Jzh9B9K6yfJD/vAeCmLafJWsAgAs0a+M/nIrQaLOlXmgyb0Xcm2e2
      PecsuMfAJIO/ULMoCBbvdjGtXhqkY3JycNtqswIDAQABAoIBAQCeQDBYXoqL4MUp
      8haQ8OyxpxGS1LAjy4xUZFrB34RxPcURY3KLXcgzE5OP/31fL4eaGb3M75ALREoQ
      hZtKfz5gwUpTaf5UUIfsW7ZuRro7tlNGoZEJHMDsn9eWJ+X+QR2Y4HJi5La//Aea
      VsLtCIcXU6NeyGDvCGtM8NSC7jvTpdtIYKxGaWOkVX0kVH76GByBr93XE7IImp7Y
      IdqhN/0wqkmXXv+LMruGzeDfm2IAtiU9VcS/oHoIEGQT84pu2JOyhQUfxlzkqMGg
      SRgOP5rrN3/GqYkY3B7O0Fx4cuKNH8ozpc1UW3pfhNYl+gbbZHq93kKxxzN8xzIu
      s5VVICEBAoGBANIZ0TS+TvlhN2GXgJFtY3Z9hnaGuyD+Kjqbsx3VWSXvQg4aY0b2
      hlgIw3C1McPiTKA3UiZuxz1Yl0xE9pFbhuuIprIE972uRz9qYrs/NtVrVWwMoar1
      DcSiTCbSOLgr9+5TQ1siI00renHtWMFrbpdoAIkYTItKIvF+lIU3s9w5AoGBAMZ+
      1UL0XMgFb/TW/kD/Rem0q8ySzev1HK00Yq5wvTHSGWU2Abtxficne4cfWzKYt5QD
      5UDQ4m8H77rbhiVgwutBRqLWIQYs3id6t8Xz4H4IeeeE2zhiXmPwKa9Hu4+ffbRM
      tcFdWq+j87l8x9wpKbYf9G1hIvDHfchsZ0WGJRZLAoGAUl4Wu4PEeFYZnSQFHn5x
      GPn7JiqJ4FRkf9ecsBx9N7cGAXts4lwxrP+6h0wx92aXvdQSW8jgSXea0SbUN4ZX
      ba2EFJSH/4/8lKsDi/8rYx4SPirxkpFB1Y3/JtURsXpjV8bCyE6o4k8iUNnJCwMw
      NyFp3FVvZMgqzNxgI54D4FkCgYAJRWFGmE1BFmftQqFrfcDRMpwXmP+/NpqZSGoX
      hbKAgjSncodQLvPadlChtgg3a8SfSDNL/LWmw/MhgiFY25UfEdRvxJqUREI4C9ZL
      i6F/oXu4IY9vqcCI4G3B/xK2mZdwdWjD2E1lCL5YeoiHMvD8za9H8JKGNnscglus
      dqCC0wKBgB5JJ4KI/xrDGG6Hh+0Eivx85kkNQu2YiAAUKbQK921x8sYC3oH/oaSL
      JsNo7mNJQTTfS7HjHPTI5H9jD9ZAvEQcE7jFPni+GAiIojJiVtYklEzoL3gx11Yj
      wy844eei6UrsJqzRPY8ZmPukuMPcb94NbH5xRk6d2cjqqmUGB6A2
      -----END RSA PRIVATE KEY-----


    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDsjCCApoCCQD0x2DFEmGEgTANBgkqhkiG9w0BAQsFADCBxjELMAkGA1UEBhMC
      SVQxDjAMBgNVBAgMBUl0YWx5MQ0wCwYDVQQHDARSb21lMRQwEgYDVQQKDAtTb3Vy
      Y2VzZW5zZTEPMA0GA1UECwwGRGV2T3BzMT0wOwYDVQQDDDRwcm9tLWV4cC1wcm9t
      ZWh0ZXVzLWV4cG9ydGVyLWRldm9wcy5hcHBzLWNyYy50ZXN0aW5nMTIwMAYJKoZI
      hvcNAQkBFiNhbGVzc2FuZHJvLmJpdG9jY2hpQHNvdXJjZXNlbnNlLmNvbTAeFw0y
      NTAxMjcxMDI4MDFaFw0yNjA2MTExMDI4MDFaMG8xCzAJBgNVBAYTAklUMQswCQYD
      VQQIDAJSTTEUMBIGA1UECgwLU291cmNlc2Vuc2UxPTA7BgNVBAMMNHByb20tZXhw
      LXByb21laHRldXMtZXhwb3J0ZXItZGV2b3BzLmFwcHMtY3JjLnRlc3RpbmcwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCi6A+KMWxShsq1AuWysjTEcDfS
      Foe49CmP3KzWF9STNrZk6nZw6gLFHSv1ArENXqsMbC7+UQ2u4zK3rtptWixDrpfK
      rm09HcX0bw7m9g/WPz1uKm3ujjoSBIVEhIU0NN50s2tDtj5MQF5Hy1xXB92knoHH
      bhSupnu+OzJTx2C1Dzs8Lj0t1hDZVx1GWu9Oc401JCuUfbMOOJaQtxqVz/NsVS/E
      G8GowCIAWiZFpDH6Lj2TBHTIA/pjh2X6bgnOH0H0rrJ8kP+8B4KYtp8lawCACzRr
      4z+citBos6VeaDJvRdybZ7Y95yy4x8Akg79QsygIFu92Ma1eGqRjcnJw22qzAgMB
      AAEwDQYJKoZIhvcNAQELBQADggEBAAYUvvewzkPWMCOe0ijeCIOWBBR6SqwUs4VI
      BhCaH3H0iLNZ4wJ17sx2+G/5YSZvJ6ZCRfeow9KYwVbzcKZ0WGlR0m1iv1xUGYEH
      7zlkoN08AT/M7e8VegoZDENoJ8BgwQCj6WzF5fzzZPMIOtgN0BtOEeunLkKtHE+6
      9s4qOQS/kDIaUPh6yaB1cssPdlNtb/2MPDBig4ugMFASz3Qoq28gB6ZX5siKqIkD
      5yKo5RAWN3QC6/jYLZEpLgJXty4F4AB3v/t9A2JWWRWM0R5MVIVREGbS3T70yQz+
      YcQilZ+tR5YNJNoT2FuWbRwPZJGS3rHfmLOGmQtm92QbZGGlnDY=
      -----END CERTIFICATE-----


    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIECjCCAvICCQDkEG3xWsXpjzANBgkqhkiG9w0BAQsFADCBxjELMAkGA1UEBhMC
      SVQxDjAMBgNVBAgMBUl0YWx5MQ0wCwYDVQQHDARSb21lMRQwEgYDVQQKDAtTb3Vy
      Y2VzZW5zZTEPMA0GA1UECwwGRGV2T3BzMT0wOwYDVQQDDDRwcm9tLWV4cC1wcm9t
      ZWh0ZXVzLWV4cG9ydGVyLWRldm9wcy5hcHBzLWNyYy50ZXN0aW5nMTIwMAYJKoZI
      hvcNAQkBFiNhbGVzc2FuZHJvLmJpdG9jY2hpQHNvdXJjZXNlbnNlLmNvbTAeFw0y
      NTAxMjcxMDIxMjZaFw0zMDAxMjYxMDIxMjZaMIHGMQswCQYDVQQGEwJJVDEOMAwG
      A1UECAwFSXRhbHkxDTALBgNVBAcMBFJvbWUxFDASBgNVBAoMC1NvdXJjZXNlbnNl
      MQ8wDQYDVQQLDAZEZXZPcHMxPTA7BgNVBAMMNHByb20tZXhwLXByb21laHRldXMt
      ZXhwb3J0ZXItZGV2b3BzLmFwcHMtY3JjLnRlc3RpbmcxMjAwBgkqhkiG9w0BCQEW
      I2FsZXNzYW5kcm8uYml0b2NjaGlAc291cmNlc2Vuc2UuY29tMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoifzYUxjYEE6V8EXyDZRauqlGxGUpFNXi0HO
      cekBBCsVK2200Gtk0veuGzXL5UUx8NChfefZVMjsjlDdy3XZNHFbhQ2pFIKwpQ0w
      3ua3LE9S64Dc6qJPECGqAMvN6/pLS0vMHnJ6fQunK0QGBwv+Do9dkbFBpoD4crVb
      S7pODBQBSjtzHX4yvQfaO6Mj5lLxvdVfGDR/5edYBaJkAQDdyqyGs/i0XFrKJ4rl
      IVoNgaceXE1OpaRpY1XIxu9oLNQKBkcjJHzkU1Oko2FnrNwR8LlZvpuSq4EWktiO
      FpiIpktsK2T/4cD5SlzJTmhHPzrZaMXwegguYMkb2RIYuH5NewIDAQABMA0GCSqG
      SIb3DQEBCwUAA4IBAQBDb+AL57C/uejTJQZ8nXrYsGJi1E+2lNYF6vVznnq/N/m/
      7s//s77N2FVX1ZuuqpjQ2j0VXQE73J8jXS1Sl9An/mlGdoL87oIvIw8kyEbkSgjj
      Le+lnXmRv8PQhmUxGP+EnuaU3zPuYUELq2gmoanlgktbd8Y2Q8ic3Npg2GZ1+mqi
      cJXsgVFK3SxGUWN6hPR9wzAQkfWGurz9DoaXn6+jNyE7cE4z5RMJoO/iCIwlTA7T
      0sat60JhaqnTX1t2z9jBmD6NKFCNy5YUS7h4mkEBkckPaF00+Z6qTReuNyWJj/i7
      pqkC8JdXwW8ItFkkwKNt3nuuwMGDiNG9lUeS29z+
      -----END CERTIFICATE-----

resources:
  requests:
    memory: "24Mi"
    cpu: "12m"
  limits:
    memory: "60Mi"
    cpu: "30m"

