# Default values for promehteus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/abitocchi/pipeline-image
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: prom-exp-promehteus-exporter-devops.apps-crc.testing

resources:
  requests:
    memory: "24Mi"
    cpu: "12m"
  limits:
    memory: "60Mi"
    cpu: "30m"

