apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"my-prometheus-exporter:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"my-prometheus-exporter\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-prometheus-exporter
      app.kubernetes.io/component: my-prometheus-exporter
      app.kubernetes.io/instance: my-prometheus-exporter
    name: my-prometheus-exporter
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: my-prometheus-exporter
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: my-prometheus-exporter
      spec:
        containers:
        - image: quay.io/abitocchi/my-prometheus-exporter:latest
          name: my-prometheus-exporter
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              memory: "24Mi"
              cpu: "12m"
            limits:
              memory: "60Mi"
              cpu: "30m"
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-prometheus-exporter
      app.kubernetes.io/component: my-prometheus-exporter
      app.kubernetes.io/instance: my-prometheus-exporter
    name: my-prometheus-exporter
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: my-prometheus-exporter
  status:
    loadBalancer: {}
kind: List
metadata: {}